
-- Add pi_payments table for storing Pi Network payment transactions
CREATE TABLE IF NOT EXISTS public.pi_payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_id TEXT NOT NULL UNIQUE,
  user_id TEXT REFERENCES public.users(id),
  txid TEXT,
  status TEXT NOT NULL,
  amount NUMERIC,
  memo TEXT,
  metadata JSONB,
  pi_payment_data JSONB,
  pi_completion_data JSONB,
  error_data JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  completed_at TIMESTAMP WITH TIME ZONE
);

-- Add wallet_address column to users if it doesn't exist
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS wallet_address TEXT;

-- Add subscription_updated_at column to users if it doesn't exist
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS subscription_updated_at TIMESTAMP WITH TIME ZONE;

-- Add index on payment_id for faster lookups
CREATE INDEX IF NOT EXISTS idx_pi_payments_payment_id ON public.pi_payments (payment_id);

-- Add index on user_id for faster user-based queries
CREATE INDEX IF NOT EXISTS idx_pi_payments_user_id ON public.pi_payments (user_id);

-- Add index on status for filtering by payment status
CREATE INDEX IF NOT EXISTS idx_pi_payments_status ON public.pi_payments (status);
